<a href="https://colab.research.google.com/github/psagrera/Data-Science-Advanced/blob/main/DeepLearning/Session1/worksheet/S1_DL_Worksheet/S1_DL_worksheet_1_TFIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


<img src="https://drive.google.com/uc?id=1zWG2FYCrmlZ8HmPjmgoIZikGW9MbrxMl" style="height: 100px">
<center style="color:#888">Módulo Data Science in IoT<br/>Asignatura Deep Learning</center>

# Worksheet S1: Introducción a TensorFlow 2.0

## Objetivos

El objetivo de este worksheet es comprender el funcionamiento básico de TensorFlow. TensorFlow es una libreria especializada en Machine Learning desarrollada por Google que se ha estandarizado tanto en el entorno empresarial como en el investigador. A lo largo de este worksheet vamos a asimilar los siguientes conceptos:
- Instalación y configuración de TensorFlow
- Representación de Tensores
- Rango y forma de los Tensores
- Tipos de Tensores en TensorFlow

## Introducción

TensorFlow es una librería muy completa que cubre todo el espectro de la inteligencia artificial, con especial énfasis en las redes neuronales. TensorFlow nace en 2015, y rápidamente se extiende en las universidades como la herramienta más potente para investigar redes neuronales profundas. Sin embargo, en las empresas, TensorFlow se combinaba con Keras, una librería de más alto nivel que simplificaba el desarrollo de proyectos basados en Deep Learning. En Septiembre de 2019, Google liberó TensorFlow 2.0, tras una modificación completa de la librería que combina lo mejor de TensorFlow y de Keras de forma nativa.

## Instalación de TensorFlow

### Google Colab

Para el desarrollo de nuestras prácticas utilizaremos Google Colab, ya que nos va a permitir desarrollar ejecutar nuestras redes en una máquina mucho más potente facilitando el aprendizaje. Google Colab ya tiene instalado TensorFlow por defecto en su entorno de desarrollo.

### Instalación de TensorFlow en nuestra máquina local

La forma más sencilla de instalar TensorFlow en nuestra máquina local es mediante la utilización de PIP.

In [13]:
pip install tensorflow

En caso de que tengamos un sistema con una GPU capaz de correr código CUDA instalaremos la siguiente versión:

In [14]:
# $ pip install tensorflow-gpu

Si utilizamos anaconda, para esta asignatura lo mejor será crear un nuevo environment e instalar:

- Tensorflow version 2
- Pandas
- Matplotlib

## Importing TensorFlow

Lo primero que tenemos que hacer para trabajar con tensorflow es importarlo. Esto permitirá a nuestra terminal python acceder a todas las clases, métodos y símbolos de TensorFlow. Normalmente se importa con el sobrenombre tf para hacer las instrucciones más cortas, de la siguiente forma:

In [15]:
# %tensorflow_version 2.x # esta linea no es necesaria si estás fuera de colab

In [16]:
import tensorflow as tf  # importamos tensorflow
print(tf.__version__) # nos aseguramos de estar usando la segunda versión

2.4.1


## Tensores

El tensor es la unidad básica de datos en TensorFlow. Un tensor es una generalización de vectores o matrices para cualquier dimensionalidad. Es decir, un tensor es un array con n dimensiones. Los tensores son el objeto principal que se manipula y transmite a lo largo de un programa en tensorflow. Cada tensor, representa una operación o unos datos que en algún momento producirán un valor.

El código en TensorFlow funciona construyendo un grafo de tensores se relacionan entre si formando nuestros modelos.

Cada tensor tiene un "data type", como por ejemplo float32, int32 o string.

Al igual que sucede con los vectores o las matrices, los tensores pueden ser objeto de operaciones como la suma, la resta, el producto, etc.

A continuación vamos a ver cómo se representan y manipulan los tensores.

### Definiendo Tensores

Vamos a ver ejemplos de definición de distintos tensore.

Símplemente tenemos que definir el valor del tensor y su tipo. Normalmente trabajaremos con tensores numéricos.

In [17]:
string = tf.Variable("tensor de tipo string", tf.string) 
number = tf.Variable(254, tf.int16)
floating = tf.Variable(3.657, tf.float64)
t1 = 3

### Rango de un Tensor

El rango de un tensor es sú número de dimensiones. En inglés se define utilizando "rank" o "degree". Todos los tensores que hemos creado previamente son tensores de rango 0, es decir, escalares.

Vamos a ver tensores de un rango superior:

In [18]:
rank1_tensor = tf.Variable(["string1"], tf.string) 
rank2_tensor = tf.Variable([["ok", "test"], ["yes", "test"]], tf.string)
t2 = [1., 2., 3.]
t3 = [[1., 2., 3.], [4., 5., 6.]]

Para determinar el rango de un tensor podemos utilizar la función tf.rank():

In [19]:
print(tf.rank(rank2_tensor))

tf.Tensor(2, shape=(), dtype=int32)


### Shape de un tensor

Los tensores, además de tener un rango, tienen también unas dimensiones, que podemos ver con la función tensor.shape

In [20]:
rank2_tensor.shape

TensorShape([2, 2])

Los tensores pueden cambiar de dimensionalidad utilizando la función tf.reshape de forma similar a lo que hemos visto con el paquete numpy:

In [21]:
tensor1 = tf.ones([1,2,3])  # tf.ones() crea un tensor de tamaño [1,2,3] lleno de unos
tensor2 = tf.reshape(tensor1, [2,3,1])  # hace un reshape a [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 es un comodín que deja espacio a tf para que calcule la dimensión por si mismo
            

El número de elementos al hacer un reshape tiene que ser el mismo que el original, de lo contrario fallará

Vamos a ver cómo han quedado nuestros tensores

In [22]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


### Tipos de tensores en tensorflow

Hay diferentes tipos de tensores, los siguientes son los más utilizados:

- Variable
Es el único tensor (de los que estamos viendo aquí) mutable, es decir, que puede cambiar su valor durante la ejecución. Por tanto, se utiliza este tipo de tensor cuando queremos almacenar datos que van a necesitar variar su valor durante la ejecución, como por ejemplo, los parámetros entrenables.

- Constant
En este tipo de tensor almacenaremos datos de tipo constante, es decir, valores que conocemos de antemano y que no cambiarán su valor durante la ejecución.

- Placeholder
Es el tipo de tensor en el que suelen almacenarse los datos de entrada o las etiquetas con las que vamos a entrenar o evaluar nuestros modelos. Definen un "contenedor" que rellenaremos justo antes de la ejecución con los datos que estemos utilizando en ese momento.

- SparseTensor
Es un tipo de tensor que se utiliza cuando tenemos matrices con muchos datos vacíos, ya que está diseñado para trabajar con este tipo de datos de forma eficiente.


## Fuentes

La mayoría de la información presentada aquí puede extenderse en el sitio oficial de TensorFlow:

https://www.tensorflow.org/guide/tensor